#!/bin/bash
set -e

app_dir=$1
bp_dir=$(cd $(dirname $0); cd ..; pwd)
export PATH=$bp_dir/vendor/node/bin:$bd_dir/node_modules/.bin:$bp_dir/scripts:$bp_dir/vendor:$PATH

echo "run_tasks/pwd: $PWD"
echo "run_tasks/app_dir: $app_dir"
echo "run_tasks/bp_dir: $bp_dir"

source $bp_dir/scripts/common.sh

echo "Getting build task"
if [ -z "$GRUNTCMD" ]; then
    # Check to see if we have a npm run build
    npm_cmd=$(cat $app_dir/package.json | jq -r .scripts.build)
    if [ -z "$npm_cmd" ]; then
        echo "No GRUNTCMD and no scripts.build"
        exit -1
    else
        echo "Using default"
        GRUNTCMD="npm run build"
    fi
fi

cd $app_dir
echo "Command: $GRUNTCMD"
$GRUNTCMD | indent
